import type { NextPage } from "next";
import Head from "next/head";
import { useActiveWeb3React } from "hooks/useActiveWeb3React";
import { useEffect } from "react";
import { injected } from "config/constants/wallets";
import { connectorLocalStorageKey } from "config/connectors/index";
import formatAddress from "functions/formatAddress";
import { ChainColor, ChainId } from "config";
import { getChainInfo } from "functions/getChainInfo";

const Home: NextPage = () => {
    const { account, chainId, error, activate } = useActiveWeb3React();
    const fontColor = ChainColor[chainId ?? ChainId.ETHEREUM]

    useEffect(() => {
        console.log(window.localStorage.getItem(connectorLocalStorageKey));

        activate(injected, undefined, true).catch((error) => {
            activate(injected);
        })
    }, [])

    return (
        <div
            style={{
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                justifyContent: "center",
                height: "100vh",
                backgroundColor: "black",
                color: fontColor,
                fontSize: "1.2rem",
                fontStyle: "bold",
            }}
        >
            <Head>
                <title>Web3 NextJS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div
                style={{
                    display: "flex",
                    flexDirection: "column",
                    alignItems: "center",
                    justifyContent: "center",
                }}
            >
                {account ? `Connected to ${formatAddress(account ?? '')} on ${getChainInfo(chainId, 'NETWORK')}` : 'Disconnected'}
            </div>
        </div>
    );
};

export default Home;
