import type { NextPage } from "next";
import Head from "next/head";
import { useActiveWeb3React } from "hooks/useActiveWeb3React";
import { BLUE, ChainColor, ChainId, WHITE } from "config";
import formatAddress from "functions/formatAddress";
import { useWeb3Modal, useWeb3ModalAccount } from '@web3modal/ethers/react';

const Home: NextPage = () => {

  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        height: "100vh",
        backgroundColor: BLUE,
        color: WHITE,
        fontSize: "1.2rem",
        fontStyle: "bold",
      }}
    >
      <div>
        <Head>
          <title>NextJS Template</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            border: "4px solid",
            borderRadius: "5px",
            padding: "8px",
            color: "#FFFFFF",
          }}
        >
         {`Welcome to the NextJS Template`}
        </div>
      </div>
    </div>
  );
};

export default Home;